pipeline {
    agent any

    stages {

        stage('Build Sportsbook image') {
            steps {
                dir("sportsbook") {
                    sh 'docker build --build-arg APP_NAME=SportsbookApp -t koodikindral/api:sportsbook .'
                }
            }
        }
      
        stage('Push Sportsbook image') {
            steps {
                dir("sportsbook") {
                    sh 'docker push koodikindral/api:sportsbook'
                }
            }
        }
                
        stage('Deploy K8S') {
            steps {
                sh 'kubectl set image deployments/sportsbook sportsbook=$(docker inspect --format="{{index .RepoDigests 0}}" koodikindral/api:sportsbook)'
            }
        }
    }
}
