pipeline {
    agent any

    stages {

        stage('Build Docker image') {
            steps {
                dir("wallet") {
                    sh 'docker build -t koodikindral/api:wallet .'
                }
            }
        }
      
        stage('Push Docker image') {
            steps {
                dir("wallet") {
                    sh 'docker push koodikindral/api:wallet'
                }
            }
        }
                
        stage('Deploy K8S') {
            steps {
                sh 'kubectl set image deployments/wallet wallet=$(docker inspect --format="{{index .RepoDigests 0}}" koodikindral/api:wallet)'
            }
        }
    }
}
