pipeline {
    agent any

    stages {

        stage('Build Docker image') {
            steps {
                dir("sportsbook") {
                    sh 'docker build -t koodikindral/api:sportsbook .'
                }
            }
        }
      
        stage('Push Docker image') {
            steps {
                dir("sportsbook") {
                    sh 'docker push koodikindral/api:sportsbook'
                }
            }
        }
                
        stage('Deploy K8S') {
            steps {
                sh 'kubectl set image deployments/wallet wallet=koodikindral/api'
                sh 'kubectl set image deployments/wallet wallet=koodikindral/api:sportsbook'
            }
        }
    }
}
