pipeline {
    agent any

    stages {

        stage('Clean') {
            steps {
                sh 'dotnet clean sportsbook'
            }
        }

        stage('Build sportsbook') {
            steps {
                sh 'dotnet build sportsbook'
            }
        }
    }
}
